This is a sandbox notebook where I check how different functions work and I am able to access and load in the arrays and files produced by other notebooks to check they are as expected. There is minimal commenting and this notebook is mainly just used for investigative purposes.

In [ ]:
from netCDF4 import Dataset
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import os
import csv
from datetime import datetime
from mpl_toolkits import mplot3d
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
import PIL
import warnings
from csv import writer
from scipy import ndimage as nd

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=False)

Mounted at /content/gdrive


In [ ]:
vector=[]
for i in range(36):
    vector.append(i)
vector = np.array(vector)
test_directory="/content/gdrive/MyDrive/Colab Notebooks/Data/Variables/"
test_name="test_file.csv"
test_path=test_directory+test_name
np.savetxt(test_path, vector)
print(vector)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [ ]:
test_directory="/content/gdrive/MyDrive/Colab Notebooks/Data/Variables/"
test_name="test_file.csv"
test_path=test_directory+test_name
counter_df = pd.read_csv(test_path)
print(counter_df)
counter_df = counter_df.to_numpy(dtype='i')
print(int(counter_df[10]))
print(counter_df)
print(len(counter_df))

    0.000000000000000000e+00
0                        1.0
1                        2.0
2                        3.0
3                        4.0
4                        5.0
5                        6.0
6                        7.0
7                        8.0
8                        9.0
9                       10.0
10                      11.0
11                      12.0
12                      13.0
13                      14.0
14                      15.0
15                      16.0
16                      17.0
17                      18.0
18                      19.0
19                      20.0
20                      21.0
21                      22.0
22                      23.0
23                      24.0
24                      25.0
25                      26.0
26                      27.0
27                      28.0
28                      29.0
29                      30.0
30                      31.0
31                      32.0
32                      33.0
33            

In [ ]:
def fill(data, invalid=None):
    """
    Replace the value of invalid 'data' cells (indicated by 'invalid') 
    by the value of the nearest valid data cell

    Input:
        data:    numpy array of any dimension
        invalid: a binary array of same shape as 'data'. True cells set where data
                 value should be replaced.
                 If None (default), use: invalid  = np.isnan(data)

    Output: 
        Return a filled array. 
    """
    #import numpy as np
    #import scipy.ndimage as nd

    if invalid is None: invalid = np.isnan(data)

    ind = nd.distance_transform_edt(invalid, return_distances=False, return_indices=True)
    return data[tuple(ind)]

In [ ]:
temp=np.zeros((10,10))
for i in range(10):
  for j in range(10):
    temp[i,j]=i-j
temp

array([[ 0., -1., -2., -3., -4., -5., -6., -7., -8., -9.],
       [ 1.,  0., -1., -2., -3., -4., -5., -6., -7., -8.],
       [ 2.,  1.,  0., -1., -2., -3., -4., -5., -6., -7.],
       [ 3.,  2.,  1.,  0., -1., -2., -3., -4., -5., -6.],
       [ 4.,  3.,  2.,  1.,  0., -1., -2., -3., -4., -5.],
       [ 5.,  4.,  3.,  2.,  1.,  0., -1., -2., -3., -4.],
       [ 6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2., -3.],
       [ 7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.],
       [ 8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1.],
       [ 9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0.]])

In [ ]:
for i in range(10):
  for j in range(10):
    if i==j:
      temp[i,j]=0
    if i==0 and j==1 or i==2 and j==3 or i==4 and j==5 or i==6 and j==7:
      temp[i,j]=0
print(temp)

[[ 0.  0. -2. -3. -4. -5. -6. -7. -8. -9.]
 [ 1.  0. -1. -2. -3. -4. -5. -6. -7. -8.]
 [ 2.  1.  0.  0. -2. -3. -4. -5. -6. -7.]
 [ 3.  2.  1.  0. -1. -2. -3. -4. -5. -6.]
 [ 4.  3.  2.  1.  0.  0. -2. -3. -4. -5.]
 [ 5.  4.  3.  2.  1.  0. -1. -2. -3. -4.]
 [ 6.  5.  4.  3.  2.  1.  0.  0. -2. -3.]
 [ 7.  6.  5.  4.  3.  2.  1.  0. -1. -2.]
 [ 8.  7.  6.  5.  4.  3.  2.  1.  0. -1.]
 [ 9.  8.  7.  6.  5.  4.  3.  2.  1.  0.]]


In [ ]:
temp_invalid = temp==0
temp_invalid

array([[ True,  True, False, False, False, False, False, False, False,
        False],
       [False,  True, False, False, False, False, False, False, False,
        False],
       [False, False,  True,  True, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False, False,
        False],
       [False, False, False, False,  True,  True, False, False, False,
        False],
       [False, False, False, False, False,  True, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True, False,
        False],
       [False, False, False, False, False, False, False,  True, False,
        False],
       [False, False, False, False, False, False, False, False,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
         True]])

In [ ]:
filled_temp = fill(temp, invalid=temp_invalid)
print(filled_temp)
print(temp)

[[ 1. -2. -2. -3. -4. -5. -6. -7. -8. -9.]
 [ 1.  1. -1. -2. -3. -4. -5. -6. -7. -8.]
 [ 2.  1.  1. -2. -2. -3. -4. -5. -6. -7.]
 [ 3.  2.  1.  1. -1. -2. -3. -4. -5. -6.]
 [ 4.  3.  2.  1.  1. -2. -2. -3. -4. -5.]
 [ 5.  4.  3.  2.  1.  1. -1. -2. -3. -4.]
 [ 6.  5.  4.  3.  2.  1.  1. -2. -2. -3.]
 [ 7.  6.  5.  4.  3.  2.  1.  1. -1. -2.]
 [ 8.  7.  6.  5.  4.  3.  2.  1.  1. -1.]
 [ 9.  8.  7.  6.  5.  4.  3.  2.  1.  1.]]
[[ 0.  0. -2. -3. -4. -5. -6. -7. -8. -9.]
 [ 1.  0. -1. -2. -3. -4. -5. -6. -7. -8.]
 [ 2.  1.  0.  0. -2. -3. -4. -5. -6. -7.]
 [ 3.  2.  1.  0. -1. -2. -3. -4. -5. -6.]
 [ 4.  3.  2.  1.  0.  0. -2. -3. -4. -5.]
 [ 5.  4.  3.  2.  1.  0. -1. -2. -3. -4.]
 [ 6.  5.  4.  3.  2.  1.  0.  0. -2. -3.]
 [ 7.  6.  5.  4.  3.  2.  1.  0. -1. -2.]
 [ 8.  7.  6.  5.  4.  3.  2.  1.  0. -1.]
 [ 9.  8.  7.  6.  5.  4.  3.  2.  1.  0.]]


In [ ]:
#the order that fill follows is left then top then down then right

In [ ]:
def checkerboard(shape):
    return np.indices(shape).sum(axis=0) % 2

In [ ]:
checker = checkerboard((120,121,121))

In [ ]:
def find_perimeter(cloud):
    missing_value_counter=0
    #initialise the vectors which will store our variables cloud perimeter, cloud fraction
    #and height, these vectors will be the response and explanatory variables for the cells,
    #respectively
    cloud_perimeter_vector=[]
    cloud_fraction_vector=[]
    height_vector=[]
    perimeter_values_vector=[]
    cloud_slice=cloud
    perimeter_values_counter=0
    #specify the kernel which allows the computation of the cloud perimeter
    k=[[[0,0,0],[0,1,0],[0,0,0]],[[0,1,0],[1,0,1],[0,1,0]],[[0,0,0],[0,1,0],[0,0,0]]]
    #cast the cloud array and kernels as a Tensorflow tensor
    cloud_tensor = tf.constant(cloud_slice, tf.float32)
    k_tensor = tf.constant(k, tf.float32)
    #perform the convolution operation to find an array showing the number of neighbouring 1s for each element
    kernel_cloud = tf.nn.convolution(tf.reshape(cloud_tensor, [1, 120, 121, 121, 1]), tf.reshape(k_tensor, [3, 3, 3, 1, 1]), padding='VALID')
    #subtract this array from 6 in every entry to find the perimeter of each element
    kernel_cloud_subtracted = tf.subtract(6,kernel_cloud)
    #remove the outer edges of the cloud array so that we can multiply by the convolved arrya entry-wise
    #this has edges removed because VALID padding is used
    cloud_tensor_reduced=cloud_tensor[1:-1,1:-1,1:-1]
    #multiply the two arrays entry-wise so that we only consider the perimeter of elements where a cloud i.e. a 1
    #exists (where a 0 exists, this entry will just be zeroed by the operation)
    cloud_perimeter_tensor=tf.math.multiply(cloud_tensor_reduced,tf.squeeze(kernel_cloud_subtracted))
    #pad with an extra row of zeros to make the domain a cubic domain of 120 entries in each dimension
    for kk in range(20):
      for jj in range(4):
        for ii in range(4):
          if (kk==19 and jj==3 and ii==3):
              #when we lie in the final cell we overlap by as much as necessary
              cloud_cell=cloud_tensor_reduced[-6:,-30:,-30:]
              cloud_perimeter_cell=cloud_perimeter_tensor[-6:,-30:,-30:]
          elif (kk==19 and jj!=3 and ii!=3):
              #when we lie in the final cell we overlap by as much as necessary
              cloud_cell=cloud_tensor_reduced[-6:,30*(jj):30*(jj+1),30*(ii):30*(ii+1)]
              cloud_perimeter_cell=cloud_perimeter_tensor[-6:,30*(jj):30*(jj+1),30*(ii):30*(ii+1)]
          elif (kk==19 and jj==3 and ii!=3):
              #when we lie in the final cell we overlap by as much as necessary
              cloud_cell=cloud_tensor_reduced[-6:,-30:,30*(ii):30*(ii+1)]
              cloud_perimeter_cell=cloud_perimeter_tensor[-6:,-30:,30*(ii):30*(ii+1)]
          elif (kk==19 and jj!=3 and ii==3):
              #when we lie in the final cell we overlap by as much as necessary
              cloud_cell=cloud_tensor_reduced[-6:,30*(jj):30*(jj+1),-30:]
              cloud_perimeter_cell=cloud_perimeter_tensor[-6:,30*(jj):30*(jj+1),-30:]
          elif (kk!=19 and jj!=3 and ii==3):
              #when we lie in the final cell we overlap by as much as necessary
              cloud_cell=cloud_tensor_reduced[6*kk:6*(kk+1),30*(jj):30*(jj+1),-30:]
              cloud_perimeter_cell=cloud_perimeter_tensor[6*kk:6*(kk+1),30*(jj):30*(jj+1),-30:]
          elif (kk!=19 and jj==3 and ii==3):
              #when we lie in the final cell we overlap by as much as necessary
              cloud_cell=cloud_tensor_reduced[6*kk:6*(kk+1),-30:,-30:]
              cloud_perimeter_cell=cloud_perimeter_tensor[6*kk:6*(kk+1),-30:,-30:]
          elif (kk!=19 and jj==3 and ii!=3):
              #when we lie in the final cell we overlap by as much as necessary
              cloud_cell=cloud_tensor_reduced[6*kk:6*(kk+1),-30:,30*(ii):30*(ii+1)]
              cloud_perimeter_cell=cloud_perimeter_tensor[6*kk:6*(kk+1),-30:,30*(ii):30*(ii+1)]
          else:
              #specify which of the 320 cells at each time step that we lie in
              cloud_cell=cloud_tensor_reduced[6*kk:6*(kk+1),30*(jj):30*(jj+1),30*(ii):30*(ii+1)]
              #specify the equivalent cell for the cloud_perimeter_tensor generated above
              cloud_perimeter_cell=cloud_perimeter_tensor[6*kk:6*(kk+1),30*(jj):30*(jj+1),30*(ii):30*(ii+1)]
          #if any value within the cell is -1 we discount the cell entirely,
          #as prescribed by the methodology
          if np.any(cloud_cell < 0):
              #increment the counter by 1 if we ignore a cell
              missing_value_counter+=1
              continue
          else:
              perimeter_values_counter+=1
              #compute the cloud fraction - divide the number of 1s by the volume of a cell
              cloud_fraction_value=(np.sum(cloud_cell))/(np.shape(cloud_cell)[0]*np.shape(cloud_cell)[1]*np.shape(cloud_cell)[2])
              cloud_fraction_value=float(cloud_fraction_value)
              #append the computed value onto the cloud fraction vector 
              cloud_fraction_vector.append(cloud_fraction_value)
              #sum over the entire 3D array to find the total perimeter - a single scalar
              cloud_perimeter_value=tf.reduce_sum(cloud_perimeter_cell)
              cloud_perimeter_value=int(cloud_perimeter_value)
              cloud_perimeter_value=float(cloud_perimeter_value/16200)
              #append the cloud perimeter value for this time step in this cell to vector
              cloud_perimeter_vector.append(cloud_perimeter_value)

              #append the height to the height vector
              height_vector.append(kk)
    cloud_perimeter_vector=np.array(cloud_perimeter_vector)
    cloud_fraction_vector=np.array(cloud_fraction_vector)
    height_vector=np.array(height_vector)
    return cloud_perimeter_vector, cloud_fraction_vector, height_vector

In [ ]:
cloud_perimeter_vector, cloud_fraction_vector, height_vector = find_perimeter(checker)

In [ ]:
cloud_perimeter_vector

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [ ]:
cloud_fraction_vector

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.

In [ ]:
height_vector

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
       13, 13, 13, 14, 14

Testing Stacking in Axis 0

In [ ]:
zero_array=np.zeros((2,3,3))
one_array=np.ones((3,3))
print(zero_array)
print(one_array)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
for i in range(10):
  zero_array=np.concatenate((zero_array,one_array.reshape(1,one_array.shape[0],one_array.shape[1])),axis=0)
print(zero_array.shape)
print(zero_array[2:,:,:])

(12, 3, 3)
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
#specify the file path
new_file_path_atmospheric = "/content/gdrive/MyDrive/Colab Notebooks/Data/Variables/Atmospheric/"
new_file_name_atmospheric = new_file_path_atmospheric + "Atmospheric_"+'sgpcogspiN1.c1.20170831.180000'+".npy"
#load in the numpy array
atmospheric_file = np.load(new_file_name_atmospheric)

In [ ]:
assert np.all(atmospheric_file[1,:,:]==atmospheric_file[90,:,:])

In [ ]:
print(atmospheric_file[:400,2,2])

[0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706
 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706
 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706
 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706
 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706
 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706
 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706
 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706
 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706
 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.8706 0.87   0.87
 0.87   0.87   0.87   0.87   0.87   0.87   0.87   0.87   0.87   0.87
 0.87   0.87   0.87   0.87   0.87   0.87   0.87   0.87   0.87   0.87
 0.87   0.87   0.87   0.87   0.87   0.87   0.87   0.87   0.87   0.87
 0.87   0.87   0.87   0.87   0.87   0.87   0.87   0.87   0.87   0.87
 0.87   0.87   0

In [ ]:
import os

In [ ]:
correct_directory = "/content/gdrive/MyDrive/Colab Notebooks/Data/Variables/Correct Atmospheric/"
test_directory = "/content/gdrive/MyDrive/Colab Notebooks/Data/Variables/Atmospheric/"
for filename in os.listdir(correct_directory):
      correct_file_path = correct_directory + filename
      test_file_path = test_directory + filename
      correct_file = np.load(correct_file_path)
      test_file = np.load(test_file_path)
      assert np.all(correct_file==test_file)
